apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        database-name: incident_db
        database-user: incident_user
        database-password: "{{ .password }}"
        database-url: "postgresql://incident_user:{{ .password }}@postgres:5432/incident_db"
  data:
    - secretKey: password
      remoteRef:
        key: /incident-portal/prod/postgres-password
