{
 "title": "Incident Portal Monitoring",
 "tags": [
  "docker",
  "prometheus",
  "incident-portal"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Backend Up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "up{job=\"backend\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(incident_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Backend Response Time p95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(incident_http_request_duration_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}"
    }
   ]
  }
 ]
}