apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incident-portal-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Donchucky21/incident-management-portal.git
    targetRevision: main
    path: gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: incident-portal-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
